### PR TITLE
Rework Slack OAuth scopes

### PR DESCRIPTION
**Pull request by johnluetke**
users:read no longer necessary, since Slack introduced users.identify.

Had to do a two-pass auth approach, because for whatever godawful reason, Slack API does not allow requesting scopes "identify" and "identity.basic" is the same request. Will appear to the user as a second authentication request, but only occurs the *very* first time the user is authorizing the app. 

Also improved the front-end error handling.

### CODE REVIEW

**Comment by Fragger** [comment]
Sign In > Cancel vs Sign In > Authorize results in an error page instead of just backing out to the sign in button page.  Also authorizations are not remembered like the slack api docs say they should be, not sure if that is a bug on their end or implementation issue?

**Comment by johnluetke** [comment]
> Also authorizations are not remembered like the slack api docs say they should be, not sure if that is a bug on their end or implementation issue?

Are you talking about after clicking "logout"?

**Comment by Fragger** [comment]
Either logout or an expired session from stat tracker resulting in the
login button showing again.  I think clicking on that should just log yoy
in without slack asking for authorization again.

**Comment by johnluetke** [comment]
Ah okay, I'm following now. 

Upon logout, the token issued by Slack is revoked. From a Stat Tracker perspective, all I can really do after that point is redirect the user to the Slack OAuth page. From what I can tell, the app never lost it's authorization to the user's Slack credentials, it just needs a new token issued. After logout, I can go into the app's configuration on the Slack platform, and see that the logged out user has still authorized the application. I think that Slack forcing the appearance of the "reauthorization" screen is a bug/issue on thier end, not an issue with the implementation.

**Comment by johnluetke** [comment]
@Fragger b7683ae should address your concerns. I just re-ordered Slack API calls. "Re-auth" will now only happen during initial registration

**Pull request merged**
